let sourceDraft=null,sourceDrag=null,sourceReturnSelection=null,sourceMarginCollapsed=false;
function actionsForNote(){return (state.sourceActions||[]).filter(item=>item.noteId===currentNote()?.id);}
function sourceParts(range){return editorRangeParts(range).filter(part=>part.end>part.start).map(part=>({blockId:part.line.dataset.blockId,start:part.start,end:part.end,text:part.span.textContent.slice(part.start,part.end),row:part.span.dataset.row===undefined?null:Number(part.span.dataset.row),column:part.span.dataset.column===undefined?null:Number(part.span.dataset.column)}));}
function selectedOrigin(){ensureRichEditor();const range=formatRange||getSelection().rangeCount&&getSelection().getRangeAt(0);if(!range)return null;const parts=sourceParts(range);if(!parts.length)return null;return {kind:'text',quote:parts.map(part=>part.text).join('\n').slice(0,4000),parts};}
function sourceTarget(item){
 const editor=$('#note-body');if(!editor||editor.tagName==='TEXTAREA')return null;
 if(item.origin.kind==='cut')return editor.querySelector(`[data-cut-id="${CSS.escape(item.origin.cutId)}"]`);
 return sourcePartTarget(item.origin.parts[0])?.span||null;
}
function sourceCard(item,compact=false){const missing=!compact&&!sourceTarget(item),status=item.kind==='task'?(item.done?'Concluída · '+formatDateTime(item.checkedAt):'Tarefa pendente'):(item.expired?'Horário passou · Reagendar':item.fired?'Alerta disparado · '+formatDateTime(item.firedAt):'Alerta · '+formatDateTime(item.due));return `<article class="source-card ${item.done||item.fired?'source-finished':''}" data-source-card="${escape(item.id)}"><div class="source-card-top">${item.kind==='task'?`<input type="checkbox" data-source-check="${escape(item.id)}" aria-label="Concluir: ${escape(item.title)}" ${item.done?'checked':''}>`:'<span aria-hidden="true">◷</span>'}<strong>${escape(item.title)}</strong></div><small class="source-status">${escape(status)}</small><blockquote>${escape(item.origin.quote)}</blockquote><div class="source-card-footer"><button class="source-origin" data-source-origin="${escape(item.id)}">${missing?'Origem removida ou alterada · Abrir nota':'↗ '+(compact?'Voltar à origem · '+escape(item.noteTitle):'Ver origem')}</button><span><button data-source-edit="${escape(item.id)}" aria-label="Editar ação" title="Editar ação">✎</button><button data-source-remove="${escape(item.id)}" aria-label="Mover ação para a lixeira" title="Mover ação para a lixeira">×</button></span></div>${missing?'<small class="source-missing">A cópia original está preservada aqui.</small>':''}</article>`;}
function bindSourceCards(root){root.querySelectorAll('[data-source-edit]').forEach(button=>button.onclick=async()=>{const item=state.sourceActions.find(item=>item.id===button.dataset.sourceEdit);if(view!=='notes'||currentNote()?.id!==item.noteId){await openSourceOrigin(item.id);}sourceReturnSelection=editorSelection();sourceDraft={id:item.id,noteId:item.noteId,origin:item.origin,title:item.title,kind:item.kind,due:item.due?localDate(new Date(item.due).getTime()):''};renderSourceMargin();$('#source-title').focus();});root.querySelectorAll('[data-source-check]').forEach(input=>input.onchange=async()=>{if(await action('source:toggle',{id:input.dataset.sourceCheck})){refreshSourceSurfaces();}else input.checked=!input.checked;});root.querySelectorAll('[data-source-origin]').forEach(button=>button.onclick=()=>openSourceOrigin(button.dataset.sourceOrigin));root.querySelectorAll('[data-source-remove]').forEach(button=>button.onclick=async()=>{if(await action('source:remove',{id:button.dataset.sourceRemove}))refreshSourceSurfaces();});}
function refreshSourceSurfaces(){if(view==='home')refreshHomePanels();else if(view==='notes')renderSourceMargin();else if(view==='tasks')renderSourceTasks();}
function renderSourceMargin(){
 if(view!=='notes'||!currentNote()||!$('#note-body'))return;
 let layout=$('.action-page');if(!layout){layout=document.createElement('div');layout.className='action-page';const editor=$('#note-body');editor.before(layout);layout.append(editor);const rail=document.createElement('aside');rail.id='source-margin';rail.className='source-margin';rail.contentEditable='false';rail.setAttribute('aria-label','Ações ligadas à página');layout.append(rail);}
 renderSourceAnchors();
 const rail=$('#source-margin'),items=actionsForNote();rail.hidden=!items.length&&!sourceDraft&&!sourceDrag;layout.classList.toggle('has-actions',!rail.hidden);layout.classList.toggle('margin-collapsed',sourceMarginCollapsed&&!sourceDraft&&!sourceDrag);
 if(sourceDraft){renderSourceComposer(rail);return;}
 rail.innerHTML=`<div class="source-heading"><h2>Ações desta nota</h2><button id="source-fold" aria-expanded="${!sourceMarginCollapsed}" aria-label="${sourceMarginCollapsed?'Abrir':'Recolher'} ações da margem" title="${sourceMarginCollapsed?'Abrir':'Recolher'} margem">${sourceMarginCollapsed?'‹':'›'}</button></div><small class="source-count">${items.filter(item=>item.kind==='task'&&!item.done).length} ${items.filter(item=>item.kind==='task'&&!item.done).length===1?'tarefa':'tarefas'} · ${items.filter(item=>item.kind==='reminder'&&!item.fired&&!item.expired).length} ${items.filter(item=>item.kind==='reminder'&&!item.fired&&!item.expired).length===1?'alerta':'alertas'}</small>${sourceDrag?'<div class="source-drop">Solte aqui para criar uma ação</div>':''}<div class="source-cards">${items.map(item=>sourceCard(item)).join('')}</div>`;bindSourceCards(rail);$('#source-fold').onclick=()=>{sourceMarginCollapsed=!sourceMarginCollapsed;renderSourceMargin();};
 rail.ondragover=event=>{if(sourceDrag){event.preventDefault();event.dataTransfer.dropEffect='copy';rail.classList.add('source-drag-over');}};
 rail.ondrop=event=>{if(!sourceDrag)return;event.preventDefault();event.stopPropagation();const origin=sourceDrag;sourceDrag=null;rail.classList.remove('source-drag-over');openSourceComposer(origin);};
}
async function openSourceComposer(origin){
 if(!origin||!currentNote())return;
 sourceMarginCollapsed=false;sourceReturnSelection=editorSelection();const noteId=currentNote().id;
 if(origin.kind==='text'&&!await saveDocument())return;
 if(currentNote()?.id!==noteId)return;
 sourceDraft={origin,noteId,title:origin.kind==='text'?origin.quote.replace(/\s+/g,' ').slice(0,160):'',kind:'task',due:'',error:''};hideEditorMenus();renderSourceMargin();$('#source-title').focus();$('#source-title').select();
}
function closeSourceComposer(){sourceDraft=null;renderSourceMargin();if(sourceReturnSelection){$('#note-body')?.focus();restoreEditorSelection(sourceReturnSelection);}sourceReturnSelection=null;}
function renderSourceComposer(rail){
 rail.innerHTML=`<form id="source-form" class="source-composer"><div class="source-heading"><h2>Criar ação</h2><button type="button" id="source-close" aria-label="Cancelar criação">×</button></div><blockquote>${escape(sourceDraft.origin.quote)}</blockquote><fieldset class="source-kind"><legend>O que fazer com isso?</legend><label><input type="radio" name="source-kind" value="task" ${sourceDraft.kind==='task'?'checked':''}>Tarefa</label><label><input type="radio" name="source-kind" value="reminder" ${sourceDraft.kind==='reminder'?'checked':''}>Lembrete</label></fieldset><label for="source-title">Próximo passo</label><textarea id="source-title" rows="3" required maxlength="500" placeholder="O que você quer fazer?">${escape(sourceDraft.title)}</textarea><div id="source-date-wrap" ${sourceDraft.kind==='task'?'hidden':''}><label for="source-due">Quando lembrar?</label><input id="source-due" type="datetime-local" value="${escape(sourceDraft.due)}"><small>O alerta toca com o app aberto.</small></div><p id="source-error" role="alert" class="source-error" hidden></p><button class="primary" id="source-submit" type="submit">${sourceDraft.kind==='task'?'Criar tarefa':'Agendar lembrete'}</button><small>Ligada a esta página. Encontre também na Página do dia${sourceDraft.kind==='reminder'?' e no calendário':''}.</small></form>`;
 if(sourceDraft.id)rail.querySelector('h2').textContent='Editar ação';$('#source-close').onclick=closeSourceComposer;$('#source-title').oninput=event=>sourceDraft.title=event.target.value;$('#source-due').oninput=event=>sourceDraft.due=event.target.value;
 rail.querySelectorAll('[name=source-kind]').forEach(input=>input.onchange=()=>{sourceDraft.kind=input.value;$('#source-date-wrap').hidden=input.value==='task';$('#source-due').required=input.value==='reminder';$('#source-submit').textContent=input.value==='task'?'Criar tarefa':'Agendar lembrete';if(input.value==='reminder'){if(!sourceDraft.due){sourceDraft.due=localDate(Date.now()+3600000);$('#source-due').value=sourceDraft.due;}$('#source-due').focus();}});
 if(sourceDraft.id){rail.querySelectorAll('[name=source-kind]').forEach(input=>input.disabled=true);$('#source-submit').textContent='Salvar ação';$('#source-due').required=sourceDraft.kind==='reminder';}
 $('#source-form').onsubmit=async event=>{event.preventDefault();const draft={...sourceDraft,title:$('#source-title').value.trim(),due:$('#source-due').value};if(draft.kind==='reminder'&&(!draft.due||new Date(draft.due).getTime()<=Date.now())){$('#source-error').hidden=false;$('#source-error').textContent='Escolha uma data e hora futuras.';return;}const button=$('#source-submit');button.disabled=true;button.textContent='Guardando…';if(await action(draft.id?'source:update':'source:create',{id:draft.id,noteId:draft.noteId,title:draft.title,kind:draft.kind,origin:draft.origin,due:draft.kind==='reminder'?new Date(draft.due).toISOString():null})){sourceDraft=null;sourceReturnSelection=null;renderSourceMargin();$('#source-margin .source-card:last-child')?.scrollIntoView({block:'nearest'});}else{button.disabled=false;button.textContent=draft.kind==='task'?'Criar tarefa':'Agendar lembrete';$('#source-error').hidden=false;$('#source-error').textContent='Não foi possível guardar. Seu texto continua aqui.';}};
}
async function openSourceOrigin(id){
 const item=(state.sourceActions||[]).find(item=>item.id===id);if(!item){toast('Esta ação foi removida.');return;}
 sourceMarginCollapsed=false;sourceDraft=null;if(currentNote()?.id!==item.noteId||view!=='notes'){if(!await action('note:select',{id:item.noteId}))return;view=state.activeView;render();}
 ensureRichEditor();renderSourceMargin();const target=sourceTarget(item);if(!target){toast('O trecho de origem mudou. A cópia original está guardada na margem.');return;}
 target.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});target.classList.add('source-focus');setTimeout(()=>target.classList.remove('source-focus'),1800);if(item.origin.kind==='text'){const part=item.origin.parts[0],start=target.textContent.indexOf(part.text),a=editorTextPoint(target,start),b=editorTextPoint(target,start+part.text.length);getSelection().setBaseAndExtent(a.node,a.offset,b.node,b.offset);target.focus({preventScroll:true});}
}
function renderSourceTasks(){let panel=$('#source-task-section');const items=(state.sourceActions||[]).filter(item=>item.kind==='task'&&item.notebookId===state.activeNotebook);if(!panel){panel=document.createElement('section');panel.id='source-task-section';panel.className='source-task-section';($('#task-list')||$('#source-task-only')||$('#page-content')).prepend(panel);}panel.innerHTML=items.length?`<h2>Da margem das notas <span>${items.filter(item=>!item.done).length} pendentes</span></h2>${items.map(item=>sourceCard(item,true)).join('')}`:'';bindSourceCards(panel);}
document.addEventListener('keydown',event=>{if(sourceDraft&&event.key==='Escape'){event.preventDefault();closeSourceComposer();}});
document.addEventListener('dragend',()=>{if(sourceDrag){sourceDrag=null;renderSourceMargin();}});

window.notebook.onSourceOrigin?.(id=>openSourceOrigin(id));

let sourceRefreshTimer;document.addEventListener('input',event=>{if(view==='notes'&&event.target.closest('#note-body')){clearTimeout(sourceRefreshTimer);sourceRefreshTimer=setTimeout(()=>{if(!sourceDraft)renderSourceMargin();},450);}});

function sourcePartTarget(part){
 const editor=$('#note-body'),line=editor?.querySelector(`[data-block-id="${CSS.escape(part.blockId)}"]`);
 const span=line&&(part.row===null?editableText(line):line.querySelector(`[data-row="${part.row}"][data-column="${part.column}"]`));
 if(span){const text=span.textContent,index=text.indexOf(part.text);if(text.slice(part.start,part.end)===part.text)return {span,start:part.start,end:part.end};if(index>=0&&index===text.lastIndexOf(part.text))return {span,start:index,end:index+part.text.length};}
 const matches=[...(editor?.querySelectorAll('.line-text')||[])].filter(span=>span.textContent.includes(part.text)&&span.textContent.indexOf(part.text)===span.textContent.lastIndexOf(part.text));
 if(matches.length===1){const span=matches[0],start=span.textContent.indexOf(part.text);return {span,start,end:start+part.text.length};}return null;
}
function renderSourceAnchors(){
 const editor=$('#note-body');if(!editor||editor.tagName==='TEXTAREA')return;
 if(!actionsForNote().length&&!editor.querySelector('[data-source-anchor],.source-media-linked'))return;
 const bookmark=editorSelection(),selection=getSelection(),wasInside=selection.rangeCount&&editor.contains(selection.anchorNode)&&editor.contains(selection.focusNode);
 editor.querySelectorAll('[data-source-anchor]').forEach(mark=>mark.replaceWith(...mark.childNodes));editor.querySelectorAll('.line-text').forEach(span=>span.normalize());
 const segments=[];for(const item of actionsForNote()){
  if(item.origin.kind==='cut'){const card=editor.querySelector(`[data-cut-id="${CSS.escape(item.origin.cutId)}"]`);if(card){card.classList.add('source-media-linked');card.dataset.sourceLabel='Ação ligada a esta mídia';}continue;}
  for(const part of item.origin.parts){const target=sourcePartTarget(part);if(target)segments.push({...target,item});}
 }
 editor.querySelectorAll('.source-media-linked').forEach(card=>{if(!actionsForNote().some(item=>item.origin.cutId===card.dataset.cutId)){card.classList.remove('source-media-linked');delete card.dataset.sourceLabel;}});
 // Work from the end so overlapping actions can share a passage without changing text offsets.
 segments.sort((a,b)=>b.start-a.start||b.end-a.end);
 for(const segment of segments){const a=editorTextPoint(segment.span,segment.start),b=editorTextPoint(segment.span,segment.end),range=document.createRange();range.setStart(a.node,a.offset);range.setEnd(b.node,b.offset);const mark=document.createElement('span');mark.dataset.sourceAnchor=segment.item.id;mark.className='source-anchor'+(segment.item.done||segment.item.fired?' source-anchor-done':'');mark.title=(segment.item.kind==='task'?'Tarefa: ':'Lembrete: ')+segment.item.title;mark.append(range.extractContents());range.insertNode(mark);}
 if(wasInside&&bookmark){restoreEditorSelection(bookmark);if(!getSelection().isCollapsed&&getSelection().rangeCount)formatRange=getSelection().getRangeAt(0).cloneRange();}
}
