(async () => {
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const assert = (condition, label) => { if (!condition) throw new Error(label); };
  const click = async (selector, delay = 180) => { document.querySelector(selector).click(); await wait(delay); };
  const fill = (selector, value, event = 'input') => { const element = document.querySelector(selector); element.value = value; element.dispatchEvent(new Event(event, { bubbles: true })); };
  const current = state => state.notes.find(note => note.id === state.selected[state.activeView]);
  await wait(200);
  assert(document.querySelector('#daily-overview')&&!document.querySelector('#daily-body'), 'Página do dia é a home inicial sem campo de anotações');
  assert(document.querySelector('.sidebar [data-view]').dataset.view === 'home', 'Caderninho é o primeiro item');
  await click('[data-view=notes]');
  assert(document.querySelector('#note-body'), 'Editor de notas');
  assert(document.querySelector('#add-cut svg') && document.querySelector('#new-note svg'), 'Ações da toolbar usam ícones');
  assert(!document.querySelector('#add-cut').textContent.includes('+') && !document.querySelector('#new-note').textContent.includes('+'), 'Ações sem prefixo +');
  assert(document.querySelector('.view-toolbar #trash-note svg') && !document.querySelector('.note-bottom #trash-note'), 'Lixeira com ícone fica na toolbar');
  assert(document.querySelector('#trash-note').previousElementSibling.classList.contains('toolbar-separator'), 'Separador antes da lixeira');
  assert(!document.querySelector('#themes-open') && !document.querySelector('#pin'), 'Temas e Fixar removidos');
  assert(document.querySelectorAll('.sidebar [data-view]').length === 6, 'Seis seções do menu');
  assert(!document.querySelector('.face') && !document.querySelector('.arm'), 'Área de escrita livre do mascote');
  assert(!document.querySelector('.ribbon') && document.querySelector('.paper-tabs'), 'Marcador do topo removido');
  const widthBeforeFold = document.querySelector('#note-body').getBoundingClientRect().width;
  const initialText = document.querySelector('#note-body').value;
  await click('#sidebar-toggle', 350);
  assert((await window.notebook.state()).sidebarCollapsed, 'Menu recolhido salvo');
  assert(document.querySelector('#sidebar').inert, 'Menu recolhido fora da interação');
  assert(document.querySelector('#sidebar-toggle').getAttribute('aria-expanded') === 'false', 'Aba indica menu recolhido');
  assert(document.querySelector('#note-body').getBoundingClientRect().width > widthBeforeFold + 80, 'Recolher libera espaço para escrita');
  assert(document.querySelector('#note-body').value === initialText, 'Texto preservado ao recolher');
  for (const name of ['close', 'minimize', 'maximize']) {
    const control = document.querySelector('#' + name);
    assert(control.closest('#sheet') && control.getBoundingClientRect().width > 0, 'Controle continua no caderno: ' + name);
  }
  await click('#sidebar-toggle', 350);
  assert(!(await window.notebook.state()).sidebarCollapsed && !document.querySelector('#sidebar').inert, 'Reabrir restaura menu');
  const originalWindow = await window.notebook.window('state');
  assert(!document.querySelector('.move-grip'), 'Label de arraste removido');
  assert(!document.querySelector('.book-header').textContent.includes('CADERNINHO'), 'Título do cabeçalho removido');
  document.querySelector('#note-body').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0, pointerId: 7 }));
  assert(!document.body.classList.contains('moving-window'), 'Editor não inicia movimento');
  document.querySelector('#new-note').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true, button: 0, pointerId: 8 }));
  assert(!document.body.classList.contains('moving-window'), 'Botão não inicia movimento');
  window.notebook.move('start', { x: 100, y: 100 });
  window.notebook.move('move', { x: 124, y: 120 });
  window.notebook.move('end'); await wait(180);
  const movedWindow = await window.notebook.window('state');
  assert(Number.isInteger(movedWindow.bounds.x) && Number.isInteger(movedWindow.bounds.y), 'Arraste usa coordenadas nativas válidas');
  assert(movedWindow.bounds.width === originalWindow.bounds.width, 'Mover mantém tamanho');
  window.notebook.move('start', { x: 124, y: 120 });
  window.notebook.move('move', { x: 100, y: 100 });
  window.notebook.move('end'); await wait(180);
  // Renderer coordinates are not forwarded to native window positioning.
  window.notebook.move('start', { x: NaN, y: Infinity });
  window.notebook.move('move', { x: Number.MAX_VALUE, y: -Number.MAX_VALUE });
  window.notebook.move('end'); await wait(100);
  assert((await window.notebook.window('state')).bounds.width === originalWindow.bounds.width, 'Coordenadas inválidas não interrompem o app');
  const beforeMaximize = await window.notebook.window('state');
  const expandedWindow = await window.notebook.window('maximize');
  await wait(180);
  assert(expandedWindow.bounds.width === Math.min(1200, expandedWindow.workArea.width), 'Maximizar amplia largura com limite');
  assert(expandedWindow.bounds.height === expandedWindow.workArea.height && expandedWindow.bounds.y === expandedWindow.workArea.y, 'Maximizar usa altura disponível');
  const restoredWindow = await window.notebook.window('maximize');
  assert(restoredWindow.bounds.height === originalWindow.bounds.height, 'Restaurar altura anterior');
  assert(restoredWindow.bounds.width === beforeMaximize.bounds.width && restoredWindow.bounds.x === beforeMaximize.bounds.x, 'Restaurar recupera largura e posição');
  assert(!document.querySelector('#quick-open')&&!window.notebook.quick,'Rascunho removido da interface e da API');
  const header = document.querySelector('.book-header');
  header.dispatchEvent(new MouseEvent('dblclick', { bubbles:true, clientY:header.getBoundingClientRect().top+3 }));
  await wait(100);
  assert((await window.notebook.window('state')).expanded, 'Dois cliques no topo maximizam');
  document.querySelector('#maximize').dispatchEvent(new MouseEvent('dblclick', { bubbles:true, clientY:header.getBoundingClientRect().top+3 }));
  await wait(100);
  assert((await window.notebook.window('state')).expanded, 'Dois cliques em um botão não maximizam');
  header.dispatchEvent(new MouseEvent('dblclick', { bubbles:true, clientY:header.getBoundingClientRect().top+3 }));
  await wait(100);
  assert(!(await window.notebook.window('state')).expanded, 'Dois cliques restauram');
  window.notebook.resize('start', { edge: 'e', x: 100, y: 100 });
  window.notebook.resize('move', { x: 145, y: 100 });
  window.notebook.resize('end'); await wait(180);
  assert((await window.notebook.window('state')).bounds.width === originalWindow.bounds.width + 45, 'Arrastar borda aumenta largura');
  window.notebook.resize('start', { edge: 'e', x: 145, y: 100 });
  window.notebook.resize('move', { x: 100, y: 100 });
  window.notebook.resize('end'); await wait(180);
  window.notebook.resize('start', { edge: 'se', x: 100, y: 100 });
  window.notebook.resize('move', { x: -10000, y: -10000 });
  window.notebook.resize('end'); await wait(180);
  const compactWindow = await window.notebook.window('state');
  assert(compactWindow.bounds.width === 620 && compactWindow.bounds.height === 520, 'Canto respeita tamanho mínimo');
  assert(document.querySelector('#note-body').getBoundingClientRect().height > 120, 'Editor utilizável no tamanho mínimo');
  const lastMenu = document.querySelector('[data-view=archive]').getBoundingClientRect();
  assert(lastMenu.bottom < innerHeight, 'Menu cabe na janela compacta');
  window.notebook.resize('start', { edge: 'se', x: 0, y: 0 });
  window.notebook.resize('move', { x: originalWindow.bounds.width - 620, y: originalWindow.bounds.height - 520 });
  window.notebook.resize('end'); await wait(180);
  await click('#new-note', 160);
  assert(document.querySelector('.flipping-sheet'), 'Virada de página');
  // Menu navigation must interrupt a turn instead of silently ignoring clicks.
  await click('[data-view=tasks]');
  assert((await window.notebook.state()).activeView === 'tasks', 'Menu funciona durante a animação');
  await click('#new-note', 1100);
  fill('#note-title', 'Lista de trabalho');
  const firstList = (await window.notebook.state()).selected.tasks;
  assert(document.querySelector('.list-date time').dateTime === current(await window.notebook.state()).created, 'Data da lista visível');
  for (const text of ['Planejar', 'Revisar']) {
    fill('#task-input', text); document.querySelector('#task-form').requestSubmit(); await wait(180);
  }
  assert(document.querySelectorAll('[data-task-id]').length === 2, 'Vários checkboxes na mesma lista');
  await click('[data-task-id]');
  fill('[data-item-text]', 'Planejar o projeto');
  await wait(180);
  const completedId = current(await window.notebook.state()).items[0].id;
  assert(current(await window.notebook.state()).items[0].done, 'Checkbox concluído');
  assert(document.querySelectorAll('.progress-squares .filled').length === 1, 'Progresso no topo acompanha checkboxes');
  await click('#new-note', 1100);
  fill('#note-title', 'Lista pessoal');
  fill('#task-input', 'Comprar café'); document.querySelector('#task-form').requestSubmit(); await wait(180);
  const secondList = (await window.notebook.state()).selected.tasks;
  assert(current(await window.notebook.state()).items.length === 1, 'Segunda lista independente');
  await click('#notes-open');
  fill('#search', 'Lista de trabalho');
  assert(document.querySelectorAll('.note-list-item').length === 1, 'Busca por lista');
  assert(document.querySelector('.note-list-item small').textContent.includes('1 / 2 concluídas'), 'Progresso organizado por lista');
  await click(`[data-note-id="${firstList}"]`, 1100);
  assert(document.querySelectorAll('[data-task-id]').length === 2 && document.querySelector('[data-task-id]').checked, 'Lista e checkbox preservados');
  await click('[data-trash-item]');
  await click('[data-view=archive]'); await click('[data-trash-type=tasks]');
  assert(document.querySelector('[data-restore-id]'), 'Tarefa individual na lixeira por tipo');
  await click('[data-restore-id]', 1100);
  assert(document.querySelector(`[data-task-id="${completedId}"]`).checked, 'Restaurar item concluído');
  await click('#trash-note', 1100);
  await click('[data-view=archive]'); await click('[data-trash-type=tasks]');
  await click('[data-restore-id]', 1100);
  assert(current(await window.notebook.state()).items.length === 2, 'Restaurar lista inteira');
  await click('[data-view=reminders]'); await click('#new-note', 1100);
  fill('#note-title', 'Fazer uma pausa');
  fill('#note-body', 'Levantar, beber água e respirar.');
  const reminderId = (await window.notebook.state()).selected.reminders;
  const future = new Date(Date.now() + 60 * 60_000);
  const local = new Date(future.getTime() - future.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
  fill('#reminder-due', local, 'change'); await wait(180);
  document.querySelector('#schedule-form').requestSubmit(); await wait(180);
  assert(current(await window.notebook.state()).enabled, 'Agendar pelo formulário');
  assert(document.querySelector('#note-body').value.includes('respirar'), 'Lembrete tem texto de nota');
  await click('#test-sound');
  await window.notebook.action('schedule:activate', { id: reminderId, due: new Date(Date.now() + 1100).toISOString() });
  await wait(2400);
  assert(current(await window.notebook.state()).fired, 'Alerta dispara no horário');
  assert(document.querySelector('#toast').textContent.includes('Fazer uma pausa'), 'Aviso do lembrete');
  await click('#trash-note', 1100);
  await click('[data-view=archive]'); await click('[data-trash-type=reminders]');
  assert(document.querySelector('[data-restore-id]'), 'Lembrete na lixeira correta');
  await click('[data-restore-id]', 1100);
  assert(document.querySelector('#note-body').value.includes('respirar'), 'Restaurar texto do lembrete');
  await click('[data-view=notes]');
  fill('#note-title', 'Uma ideia para guardar');
  fill('#note-body', 'Salvamento verificado.\nSegunda linha preservada.');
  await wait(220);
  await click('#trash-note', 1100);
  await click('[data-view=archive]');
  await click('[data-trash-type=notes]');
  assert(document.querySelector('[data-restore-id]'), 'Nota na lixeira correta');
  await click('[data-restore-id]', 1100);
  assert(document.querySelector('#note-body').value.includes('Segunda linha'), 'Restaurar nota');
  for (const selectedView of ['tasks', 'reminders', 'archive', 'notes']) {
    await click(`[data-view="${selectedView}"]`);
    assert((await window.notebook.state()).activeView === selectedView, 'Clique no menu: ' + selectedView);
  }
  await click('#notes-open');
  await click('[data-note-id=welcome]', 1100);
  document.querySelector('#toast').hidden = true;
  const body = document.querySelector('#note-body').getBoundingClientRect();
  assert(body.width > 300 && body.height > 180, 'Área de escrita legível');
  const sample = await window.notebook.state();
  assert(sample.storagePath.endsWith('notebook.sqlite'), 'SQLite em uso');
  return { pages: sample.notes.length, lists: sample.notes.filter(n => n.type === 'tasks').length, reminderNotes: sample.notes.filter(n => n.type === 'reminders').length, errors: window.smokeErrors };
})().catch(error => { throw new Error(error.stack); })
