(async () => {
  const wait = ms => new Promise(resolve => setTimeout(resolve, ms));
  const assert = (value, label) => { if (!value) throw new Error(label); };
  const click = async selector => { document.querySelector(selector).click(); await wait(120); };
  await click('[data-view=reminders]');
  assert($('#calendar-month'), 'Lembretes abre no calendário');
  assert(document.querySelectorAll('[data-calendar-day]').length === 42, 'Calendário tem seis semanas completas');
  const originalMonth = $('#calendar-month').textContent;
  await click('#calendar-next');
  assert($('#calendar-month').textContent !== originalMonth, 'Navega para o próximo mês');
  await click('#calendar-prev');
  assert($('#calendar-month').textContent === originalMonth, 'Volta ao mês anterior');
  await click('#calendar-prev'); await click('#calendar-today');
  assert($('#calendar-month').textContent === originalMonth, 'Hoje volta ao mês atual');
  const tomorrow = new Date(); tomorrow.setDate(tomorrow.getDate() + 1);
  const day = calendarDateKey(tomorrow);
  await click(`[data-calendar-day="${day}"]`);
  assert(document.querySelector(`[data-calendar-day="${day}"]`).getAttribute('aria-pressed') === 'true', 'Seleciona dia');
  await click('#new-note'); await wait(950);
  const id = currentNote().id;
  assert($('#reminder-due').value.startsWith(day), 'Novo lembrete usa a data selecionada');
  $('#note-title').value = 'Visita ao calendário'; $('#note-title').dispatchEvent(new Event('input'));
  $('#note-body').value = 'Um lembrete criado pelo dia escolhido.'; $('#note-body').dispatchEvent(new Event('input'));
  await wait(100);
  $('#schedule-form').requestSubmit(); await wait(150);
  assert(currentNote().enabled, 'Agenda lembrete na data escolhida');
  await click('#back-calendar');
  assert(document.querySelector(`[data-calendar-day="${day}"] .calendar-dots i`), 'Dia agendado mostra bullet');
  assert(document.querySelector(`[data-calendar-note="${id}"]`), 'Agenda do dia mostra lembrete');
  await click(`[data-calendar-note="${id}"]`); await wait(950);
  assert($('#note-title').value === 'Visita ao calendário', 'Abre lembrete sem duplicar');
  await click('#back-calendar');
  const cancelled = await window.notebook.action('schedule:cancel', { id }); state = cancelled; renderReminderCalendar();
  const remaining = calendarReminders().filter(note => calendarDateKey(new Date(note.scheduledAt)) === day);
  assert(!remaining.some(note => note.id === id), 'Cancelamento remove o alerta da agenda');
  assert(document.querySelectorAll(`[data-calendar-day="${day}"] .calendar-dots i`).length === Math.min(4, remaining.length), 'Cancelamento preserva as marcações dos outros lembretes');
  assert(document.querySelector(`.calendar-drafts [data-calendar-note="${id}"]`), 'Lembrete cancelado continua acessível');
  await window.notebook.action('schedule:activate', { id, due: new Date(day + 'T09:00:00').toISOString() });
  state = await window.notebook.state(); renderReminderCalendar();
  return { errors:window.smokeErrors, id, day };
})()
