const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('notebook', {
  onDayUpdated: callback => ipcRenderer.on('notebook:day-updated', (_event, state) => callback(state)),
  onHistory: callback => ipcRenderer.on('notebook:history', (_event, direction) => callback(direction)),
  onSourceOrigin: callback => ipcRenderer.on('notebook:source-origin', (_event, id) => callback(id)),
  related: id => ipcRenderer.invoke('related:query', id),
  relatedRetry: () => ipcRenderer.invoke('related:retry'),
  onRelatedUpdated: callback => ipcRenderer.on('related:updated', () => callback()),
  state: () => ipcRenderer.invoke('notebook:state'),
  action: (action, input) => ipcRenderer.invoke('notebook:action', action, input),
  purge: (kind, id) => ipcRenderer.invoke('notebook:purge', kind, id),
  exportPDF: id => ipcRenderer.invoke('notebook:export-pdf',id),
  sound: () => ipcRenderer.invoke('notebook:sound'),
  pdf: input => ipcRenderer.invoke('cuts:pdf', input),
  image: input => ipcRenderer.invoke('cuts:image', input),
  link: input => ipcRenderer.invoke('cuts:link', input),
  editorContextMenu: request => ipcRenderer.invoke('editor:context-menu', request),
  boardOpen: noteId => ipcRenderer.invoke('board:open', noteId),
  boardSave: input => ipcRenderer.invoke('board:save', input),
  boardFile: input => ipcRenderer.invoke('board:file', input),
  boardAttachImage: input => ipcRenderer.invoke('board:attach-image', input),
  boardThumbnail: input => ipcRenderer.invoke('board:thumbnail', input),
  boardThumbnailRead: noteId => ipcRenderer.invoke('board:thumbnail-read', noteId),
  boardExport: input => ipcRenderer.invoke('board:export', input),
  pipelineColumn: input => ipcRenderer.invoke('pipeline:column', input),
  taskCreate: input => ipcRenderer.invoke('task:create', input),
  taskUpdate: input => ipcRenderer.invoke('task:update', input),
  taskMove: input => ipcRenderer.invoke('task:move', input),
  taskTrash: taskId => ipcRenderer.invoke('task:trash', taskId),
  taskRestore: taskId => ipcRenderer.invoke('task:restore', taskId),
  taskOpen: taskId => ipcRenderer.invoke('task:open', taskId),
  taskComment: input => ipcRenderer.invoke('task:comment', input),
  taskAttachImage: input => ipcRenderer.invoke('task:attach-image', input),
  openLink: url => ipcRenderer.invoke('notebook:open-link',url),
  openCut: id => ipcRenderer.invoke('cuts:open', id),
  onCutsUpdated: callback => ipcRenderer.on('notebook:cuts-updated', (_event, state) => callback(state)),
  resize: (phase, input) => ipcRenderer.send('notebook:resize', phase, input),
  move: phase => ipcRenderer.send('notebook:move', phase),
  onWindowState: callback => ipcRenderer.on('notebook:window-state', (_event, info) => callback(info)),
  onCommand: callback => { const listener = (_event, command) => callback(command); ipcRenderer.on('notebook:command', listener); return () => ipcRenderer.removeListener('notebook:command', listener); },
  noteCommands: commands => ipcRenderer.send('notebook:note-commands', commands),
  windowButtons: position => ipcRenderer.send('notebook:window-buttons', position),
  window: action => ipcRenderer.invoke('notebook:window', action),
  onNavigate: callback => ipcRenderer.on('notebook:navigate', (_event, state) => callback(state)),
  onReminder: callback => ipcRenderer.on('notebook:reminder', (_event, reminders) => callback(reminders)),
  onSaveError: callback => ipcRenderer.on('notebook:save-error', (_event, message) => callback(message))
});
